[package]
name = "horizon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.8.0"
mac_address = "1.1.5"
sysinfo = "0.30.5"
blake3 = "1.5.0"
hex = "0.4.3"
double-ratchet-2 = { version = "0.3.6", features = ["ring"] }

secrecy = { version = "0.8.0", features = ["alloc"] }
zeroize = "1.7.0"
